/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAxelarGasService } from './IAxelarGasService'
export type { IERC20 } from './IERC20'
export type { IUpgradable } from './IUpgradable'
