export { default as Departures } from './Departures'
export { default as Landing } from './Landing'
export { default as Rent } from './Rent'
export { default as RentCheckout } from './RentCheckout'
export { default as Temp } from './Temp'
