/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAxelarGasService__factory } from "./IAxelarGasService__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IUpgradable__factory } from "./IUpgradable__factory";
