/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DummyCoin__factory } from "./DummyCoin__factory";
export { NFTDummy__factory } from "./NFTDummy__factory";
